# Site settings
title: FABERNOVEL US
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/fabernovel-us"
url: "http://fabernovel.github.io"
twitter_username: fabernovel_us
github_username:  fabernovel

# Build settings
markdown: kramdown
permalink: pretty
